version: '3.9'

services:

  server:
    container_name: camagru-server
    restart: always
    build:
      context: ./camagru
      dockerfile: dockerfile
    ports:
      - "5000:8080"
    volumes:
      - ./camagru:/app
      - /app/bin
      - /app/out


  mongo:
    image: mongo
    container_name: mongo-camagru
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
