version: '3.9'

services:

  server:
    container_name: camagru-server
    restart: always
    build:
      context: ./camagru
      dockerfile: dockerfile
    expose:
      - "5084"
    volumes:
      - ./camagru:/app
      - /app/bin
      - /app/out
    networks:
      - frontend-network
      - backend-network


  mongo:
    image: mongo
    container_name: camagru-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - backend-network

  nginx:
    build:
      context: ./nginx
      dockerfile: dockerfile
    container_name: camagru-nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
  
