# Use the official Nginx image as the base image
FROM nginx:latest

# Install OpenSSL to generate self-signed certificate
RUN apt-get update && \
    apt-get install -y openssl

# Set the working directory
WORKDIR /etc/nginx

# Generate a self-signed SSL certificate
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/nginx-selfsigned.key -out /etc/nginx/nginx-selfsigned.crt -subj "/C=US/ST=State/L=City/O=Organization/OU=Unit/CN=localhost"

# Copy the Nginx configuration file
# Expose ports
EXPOSE 80
EXPOSE 443

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
